# Generated by Django 3.1.2 on 2020-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20201024_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
