# Generated by Django 3.1.2 on 2020-10-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_status',
            field=models.BooleanField(default=False),
        ),
    ]
