# Generated by Django 3.1.2 on 2020-10-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20201024_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
